env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions:
    - '.setup.ts'
plugins:
  - react
  - jest-dom
  - testing-library
  - '@typescript-eslint'
rules:
  'react/react-in-jsx-scope': 'off'
  '@typescript-eslint/dot-notation': 'error'
  '@typescript-eslint/restrict-template-expressions': 'off'
  '@typescript-eslint/no-misused-promises': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  'no-unused-vars': 'off'
  '@typescript-eslint/no-unused-vars': 'warn'
